dist: xenial
language:
  - cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - g++-5
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -Drtff_use_mkl=OFF ..
  - make
  - "./src/rtff/rtff_test"
  - make install
  # also test the rtff wisdom
  - cd .. && mkdir -p build-wisdom && cd build-wisdom
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -Drtff_use_mkl=OFF -Drtff_fftw_use_wisdom=ON ..
  - make
  # first will take a long time
  - "./src/rtff/rtff_test"
  # second should be swift
  - "./src/rtff/rtff_test"
