dist: trusty
language:
  - cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - g++-5
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -Drtff_use_mkl=OFF ..
  - make
  - "./src/rtff/rtff_test"
  - make install
