version: 1.0.{build}

image:
  - Visual Studio 2015
  - Visual Studio 2017

install:
  - ps: (new-object net.webclient).DownloadFile('https://s3.amazonaws.com/audionamix-public/w_mkl_2017.3.210.exe', 'C:/users/appveyor/w_mkl_2017.3.210.exe')
  - cmd : C:/users/appveyor/w_mkl_2017.3.210.exe -f C:/users/appveyor --s --x
  - cmd : C:/users/appveyor/setup.exe install --output=output --eula=accept
  - cmd : cd "C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2017/windows/mkl/bin/"
  - cmd : mklvars.bat intel64 #Fills the env variables MKLROOT LIB INCLUDE

build_script:
  - cd C:\projects\rtff-0j7kw
  - mkdir build
  - cd build
  - cmake -Drtff_use_mkl=ON ..
  - cmake --build .

test_script:
  - cmd: C:/projects/rtff-0j7kw/build/src/rtff/Debug/rtff_test.exe --gtest_output=xml:tests.xml

after_test:
   - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
